# Generated by Django 5.0.6 on 2024-07-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemissued',
            name='quantity',
        ),
        migrations.AddField(
            model_name='itemissued',
            name='in_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='In Quantity'),
        ),
        migrations.AddField(
            model_name='itemissued',
            name='out_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Out Quantity'),
        ),
    ]
