# Generated by Django 5.0.6 on 2024-07-04 08:47

import Master.myvalidator
import Master.uploader
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_holder_name', models.CharField(max_length=255, verbose_name='Account Holder Name')),
                ('account_no', models.IntegerField(verbose_name='Account Number')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Bank Name')),
                ('ifsc_code', models.CharField(max_length=255, verbose_name='IFSC Code')),
                ('bank_branch', models.CharField(max_length=255, verbose_name='Bank Branch')),
                ('passbook', models.FileField(blank=True, null=True, upload_to=Master.uploader.staff_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'webp'])], verbose_name='Passbook')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.company', verbose_name='Company')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.staff', verbose_name='Staff')),
            ],
            options={
                'verbose_name': 'Bank Detail',
                'verbose_name_plural': 'Bank Details',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aadhar_no', models.CharField(help_text='Only numbers are allowed.', max_length=12, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='Aadhar Number must be number!!!'), django.core.validators.MinLengthValidator(12, 'Aadhar number must be have at least 12 digits!!!'), django.core.validators.MaxLengthValidator(12, 'Aadhar number must be 12 digits!!!')], verbose_name='Aadhar Number')),
                ('pan_no', models.CharField(max_length=10, validators=[Master.myvalidator.pan_validator], verbose_name='Pan Number')),
                ('aadhar_document', models.FileField(help_text='Upload Aadhar card..', upload_to=Master.uploader.staff_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf', 'png', 'jpg', 'jpeg', 'webp'])], verbose_name='Aadhar Document')),
                ('pan_document', models.FileField(help_text='Upload Pan card..', upload_to=Master.uploader.staff_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf', 'png', 'jpg', 'jpeg', 'webp'])], verbose_name='Pan Document')),
                ('resume', models.FileField(blank=True, help_text='Upload Resume..', null=True, upload_to=Master.uploader.staff_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf', 'png', 'jpg', 'jpeg', 'webp'])], verbose_name='Resume')),
                ('offer_letter', models.FileField(blank=True, help_text='Upload Offer Letter..', null=True, upload_to=Master.uploader.staff_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf', 'png', 'jpg', 'jpeg', 'webp'])], verbose_name='Offer Letter')),
                ('joining_letter', models.FileField(blank=True, help_text='Upload Joining Letter..', null=True, upload_to=Master.uploader.staff_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf', 'png', 'jpg', 'jpeg', 'webp'])], verbose_name='Joining Letter')),
                ('resignation_letter', models.FileField(blank=True, help_text='Upload Resignation Letter..', null=True, upload_to=Master.uploader.staff_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf', 'png', 'jpg', 'jpeg', 'webp'])], verbose_name='Resignation Letter')),
                ('other_document', models.FileField(blank=True, help_text='Upload Other Document..', null=True, upload_to=Master.uploader.staff_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf', 'png', 'jpg', 'jpeg', 'webp'])], verbose_name='Other Document')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.company', verbose_name='Company')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.staff', verbose_name='Staff')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('education', models.CharField(choices=[('10th', '10th'), ('12th', '12th'), ('UG', 'Under Graduation'), ('PG', 'Post Graduation'), ('Other', 'Other')], max_length=15, verbose_name='Education Type')),
                ('score', models.CharField(max_length=50, verbose_name='Score')),
                ('document', models.FileField(help_text='Upload education certificate..', upload_to='auth/agent/education', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf', 'png', 'jpg', 'jpeg', 'webp'])])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.company', verbose_name='Company')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.staff', verbose_name='Staff')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn Link')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name=' Twitter Link')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook Link')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram Link')),
                ('thread', models.URLField(blank=True, null=True, verbose_name='Thread Link')),
                ('github', models.URLField(blank=True, null=True, verbose_name='Github Link')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.company', verbose_name='Company')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.staff', verbose_name='Staff')),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Media',
            },
        ),
    ]
