# Generated by Django 5.0.6 on 2024-06-28 12:11

import Master.uploader
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('expense_head', models.CharField(max_length=250, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9\\s]*$', message='Expense head must be Alphanumeric!!!')], verbose_name='expense head')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Head',
                'verbose_name_plural': 'Heads',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('name', models.CharField(max_length=250, validators=[django.core.validators.RegexValidator('^[a-zA-ZÀ-ÿ\\s]*$', message='Name must be Alphabet!!!')], verbose_name='name')),
                ('invoice_no', models.CharField(blank=True, max_length=300, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9\\s]*$', message='Invoice number must be Alphanumeric!!!')], verbose_name='invoice number')),
                ('date', models.DateField(verbose_name='date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('bill', models.FileField(help_text='Upload document..', upload_to=Master.uploader.expense_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf', 'png', 'jpg', 'jpeg', 'webp'])], verbose_name='Bill')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('is_paid', models.BooleanField(default=False, verbose_name='is paid')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.company', verbose_name='Company')),
                ('expense_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Expense.head', verbose_name='Expense head')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
            },
        ),
    ]
