# Generated by Django 5.0.6 on 2024-06-26 10:42

import Master.uploader
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='bill',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=Master.uploader.expense_directory_path, verbose_name='bill'),
        ),
    ]
