# Generated by Django 5.0.6 on 2024-06-26 10:34

import Master.uploader
import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Company Type')),
            ],
            options={
                'verbose_name': 'Company Type',
                'verbose_name_plural': 'Company Types',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('company_code', models.CharField(max_length=6, unique=True, verbose_name='Company Code')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Company Name')),
                ('registered_office_address', models.TextField(verbose_name='Registered Office Address')),
                ('company_logo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=Master.uploader.company_directory_path)),
                ('company_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Authentication.companytype', verbose_name='Company Type')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
