# Generated by Django 5.0.6 on 2024-06-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_handicapped',
            field=models.BooleanField(default=False, verbose_name='Is Handicapped'),
        ),
        migrations.AddField(
            model_name='staff',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='experience',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Experience'),
        ),
    ]
