# Generated by Django 5.0.6 on 2024-06-28 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Certificate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idcard',
            options={'verbose_name': 'ID Card', 'verbose_name_plural': 'ID Cards'},
        ),
    ]
